resolver: lts-14.7

extra-deps:
  - diff-parse-0.2.1
  - optparse-applicative-0.15.0.0
  - relude-0.6.0.0
  - servant-github-webhook-0.4.2.0

  - github-0.22
  - github-webhooks-0.11.0
  - binary-instances-1    # for github

  - hlint-2.2.2
  - ghc-lib-parser-8.8.0.20190723  # for hlint
